/**
 * Goose animation clips, generated by sampling functions rather than by hand-
 * placed keys. Motion this repetitive is easier to tune as maths — one number
 * changes the whole cycle, and the loop is seamless by construction because the
 * sampled functions are periodic.
 */
import * as THREE from "three";

/** Keys per cycle. Enough that linear quaternion interpolation reads smooth. */
const SAMPLES = 32;

type EulerFn = (phase: number) => [number, number, number];
type VecFn = (phase: number) => [number, number, number];

function times(duration: number): number[] {
  return Array.from(
    { length: SAMPLES + 1 },
    (_, i) => (i / SAMPLES) * duration,
  );
}

function quatTrack(
  bone: string,
  duration: number,
  f: EulerFn,
): THREE.QuaternionKeyframeTrack {
  const t = times(duration);
  const values: number[] = [];
  const q = new THREE.Quaternion();
  const e = new THREE.Euler();
  for (let i = 0; i <= SAMPLES; i++) {
    const [x, y, z] = f(i / SAMPLES);
    q.setFromEuler(e.set(x, y, z, "XYZ"));
    values.push(q.x, q.y, q.z, q.w);
  }
  return new THREE.QuaternionKeyframeTrack(`${bone}.quaternion`, t, values);
}

function vecTrack(
  bone: string,
  duration: number,
  f: VecFn,
): THREE.VectorKeyframeTrack {
  const t = times(duration);
  const values: number[] = [];
  for (let i = 0; i <= SAMPLES; i++) values.push(...f(i / SAMPLES));
  return new THREE.VectorKeyframeTrack(`${bone}.position`, t, values);
}

const TAU = Math.PI * 2;

/**
 * The waddle.
 */
export function waddleClip(duration = 0.92): THREE.AnimationClip {
  const step = (p: number) => Math.sin(p * TAU);
  const doubleStep = (p: number) => Math.sin(p * TAU * 2);

  return new THREE.AnimationClip("waddle", duration, [
    // Rock and bob. The bob is lifted so the goose never sinks below rest.
    vecTrack("root", duration, (p) => [
      step(p) * 0.014,
      0.019 * (1 - Math.cos(p * TAU * 2)) * 0.5,
      0,
    ]),
    quatTrack("hips", duration, (p) => [0, step(p) * 0.07, step(p) * 0.155]),
    quatTrack("spine", duration, (p) => [
      doubleStep(p) * 0.02,
      step(p) * -0.03,
      step(p) * -0.04,
    ]),
    quatTrack("chest", duration, (p) => [
      doubleStep(p) * 0.025,
      step(p) * -0.02,
      step(p) * -0.05,
    ]),

    // Legs, half a cycle apart.
    quatTrack("thigh.L", duration, (p) => [step(p) * 0.42, 0, 0]),
    quatTrack("thigh.R", duration, (p) => [-step(p) * 0.42, 0, 0]),
    // Knee folds only on the lift, so the swing leg clears the ground.
    quatTrack("shin.L", duration, (p) => [-Math.max(0, step(p)) * 0.55, 0, 0]),
    quatTrack("shin.R", duration, (p) => [-Math.max(0, -step(p)) * 0.55, 0, 0]),
    // Ankle counter-rotates to keep the foot roughly flat through the step.
    quatTrack("foot.L", duration, (p) => [
      -step(p) * 0.2 + Math.max(0, step(p)) * 0.4,
      0,
      0,
    ]),
    quatTrack("foot.R", duration, (p) => [
      step(p) * 0.2 + Math.max(0, -step(p)) * 0.4,
      0,
      0,
    ]),

    // Neck counter-rolls against the hips so the head stays roughly level —
    // the same reflex that keeps a walking bird's eyes stable.
    quatTrack("neck1", duration, (p) => [
      doubleStep(p) * 0.03,
      0,
      step(p) * -0.05,
    ]),
    quatTrack("neck2", duration, (p) => [
      doubleStep(p) * 0.025,
      0,
      step(p) * -0.04,
    ]),
    quatTrack("neck3", duration, (p) => [
      doubleStep(p) * 0.02,
      0,
      step(p) * -0.03,
    ]),
    quatTrack("neck4", duration, (p) => [
      doubleStep(p) * 0.02,
      0,
      step(p) * -0.02,
    ]),
    // The head bob. Real birds thrust and hold rather than oscillating; this is
    // the cheap sinusoidal approximation of it and reads correctly at speed.
    quatTrack("head", duration, (p) => [
      doubleStep(p) * -0.09,
      0,
      step(p) * 0.05,
    ]),

    quatTrack("tail", duration, (p) => [0, step(p) * 0.12, step(p) * 0.08]),
    quatTrack("wing.L", duration, (p) => [0, 0, doubleStep(p) * 0.035]),
    quatTrack("wing.R", duration, (p) => [0, 0, -doubleStep(p) * 0.035]),
  ]);
}

/**
 * Idle. Deliberately almost nothing — a slow breath and a drift in the neck.
 * The cursor tracking supplies the life; a busy idle underneath it reads as
 * twitchy rather than alive.
 */
export function idleClip(duration = 5.4): THREE.AnimationClip {
  const slow = (p: number, off = 0) => Math.sin(p * TAU + off);

  return new THREE.AnimationClip("idle", duration, [
    vecTrack("root", duration, (p) => [
      0,
      0.006 * (1 - Math.cos(p * TAU * 2)) * 0.5,
      0,
    ]),
    quatTrack("hips", duration, (p) => [0, 0, slow(p) * 0.022]),
    quatTrack("spine", duration, (p) => [slow(p, 0.6) * 0.012, 0, 0]),
    quatTrack("neck1", duration, (p) => [
      slow(p, 0.4) * 0.03,
      slow(p, 1.1) * 0.05,
      0,
    ]),
    quatTrack("neck2", duration, (p) => [
      slow(p, 0.8) * 0.025,
      slow(p, 1.4) * 0.04,
      0,
    ]),
    quatTrack("neck3", duration, (p) => [
      slow(p, 1.2) * 0.02,
      slow(p, 1.7) * 0.035,
      0,
    ]),
    quatTrack("neck4", duration, (p) => [
      slow(p, 1.6) * 0.02,
      slow(p, 2.0) * 0.03,
      0,
    ]),
    quatTrack("head", duration, (p) => [
      slow(p, 2.0) * 0.03,
      slow(p, 2.3) * 0.04,
      0,
    ]),
    quatTrack("tail", duration, (p) => [0, slow(p, 0.9) * 0.05, 0]),
  ]);
}
